### ISSUE TITLE
Feature Request: Ability to mute all default debug/info messages in favor of a custom logger

### ISSUE THREAD

**Issue by zontreck** [cinderblocks/libremetaverse#15]
I personally use a custom logger for my bot, would be nice if i could disable the messages to only use the console output i want.

**Comment by Madpeterz** [comment]
#13 covers this

**Comment by zontreck** [comment]
#13 appears to cover this issue. However it does not appear to have been merged, it was closed and the branch deleted.

**Comment by Madpeterz** [comment]
yeah im reworking it ^+^

**Comment by Madpeterz** [comment]
there we go:
https://github.com/cinderblocks/libremetaverse/pull/17
a much nicer pull request I think

**Comment by zontreck** [comment]
Okay cool. I'm keeping an eye for when it's merged. Eager to silence a lot of the spam on my bot's console window.

**Comment by cinderblocks** [comment]
Muting debug/info messages is already supported in log4net. https://logging.apache.org/log4net/release/config-examples.html
