### ISSUE TITLE
Request: Remove Microsoft.Experimental.Collections

### ISSUE THREAD

**Issue by Madpeterz** [cinderblocks/libremetaverse#21]
with a bit of work we can remove the link to Microsoft.Experimental.Collections
by using a Dictionary and a List as a replacement (Used in file: AppearanceManager.cs )

**Comment by cinderblocks** [comment]
What is wrong with Microsoft.Experimental.Collections?

**Comment by Madpeterz** [comment]
- it also creates warnings when building the nuget packages because its in a dev state.
- its only used in appearance manager (that im aware of).
- it can be replace with ease to reduce the number of 3rd party requirements.

**Comment by Madpeterz** [comment]
Closed - No longer tracking this git
