### ISSUE TITLE
Requesting group members for a large group times out or never returns anything

### ISSUE THREAD

**Issue by zontreck** [cinderblocks/libremetaverse#22]
If requesting group member lists for a very large group containing thousands of members, the request never appears to ever complete. But for significantly smaller groups the requests will complete, sometimes with a inaccurate number of members as compared to the GroupMemberCount property of the GroupProfile.

**Comment by zontreck** [comment]
After opening the ticket i tested with a significantly smaller group, and while the requests do complete, they do not fully grab the member lists. For a group of 10 members, it would only grab 9. For a group of 1970 members, it would only grab 1771, and for a group of 98k members, it would only grab 0

**Comment by zontreck** [comment]
And the Member Reply event is always triggered.. I did not realize this with the 98k one as it was returning 0 members, but the event does fire, its just that it returns a empty array.

**Comment by cinderblocks** [comment]
This is a server bug, not viewer https://jira.secondlife.com/browse/BUG-9393

**Comment by zontreck** [comment]
Is there no way to work around this? According to that jira it's been open and acknowledged for years.  What if LibreMetaverse were to request smaller chunks until all information is obtained? Does the server allow for offset requests?
