### ISSUE TITLE
Many functions in InventoryManager are dead

### ISSUE THREAD

**Issue by zontreck** [cinderblocks/libremetaverse#27]
As can be seen in this example of code: https://github.com/zontreck/BotCore5/blob/master/Visitors/Greeter.cs#L159-L188

It does not work. It continually fails to find the requested inventory item, and in code... https://github.com/zontreck/BotCore5/blob/master/Program.cs#L297-L343

I have it set up to try to request virtually all items as well as save the inventory cache to disk, and restore the cache when next logging in. Saving cache fails as does loading it from disk.

**Comment by cinderblocks** [comment]
The example links are no longer valid.

Saving and restoring from cache should work again.
