### ISSUE TITLE
missing "Parcel" settings

### ISSUE THREAD

**Issue by Madpeterz** [cinderblocks/libremetaverse#42]
Parcel settings that are not flags are currently missing.

from my first pass looking into this it seems at some point the parcel data was expanded to include these
values

SeeAVs
AnyAVSounds
GroupAVSounds

I will have a play around with unpacking parcel data but if anyone else wants to beat me to it you are more than
welcome to

**Comment by Madpeterz** [comment]
it looks like its already there but not handled

**Comment by Madpeterz** [comment]
I have a working patch but its untested in non SL grids

**Comment by Madpeterz** [comment]
https://github.com/cinderblocks/libremetaverse/pull/43

**Comment by cinderblocks** [comment]
Added a more comprehensive change in 1.6.1
