### ISSUE TITLE
Client-Side baking is broken

### ISSUE THREAD

**Issue by RussoTheDev** [cinderblocks/libremetaverse#44]
Hi,

The client-side baking not working at all because conditional brake fills only the first item of the `VisualParam` array in the instance of `AgentSetAppearancePacket` :
https://github.com/cinderblocks/libremetaverse/blob/a15c3af511c39c7e4bcb44cc4213b3e69f382d8e/LibreMetaverse/AppearanceManager.cs#L2252
This condition leads to null ref exception in the next loop:
https://github.com/cinderblocks/libremetaverse/blob/a15c3af511c39c7e4bcb44cc4213b3e69f382d8e/LibreMetaverse/AppearanceManager.cs#L2255-L2259
Also if I switch the comparison to `if (vpIndex >= nrParams) break;`, the character appears without textures and alpha.

This issue appears on opensim instance but not in SL because LL server supports server-side baking

**Comment by Madpeterz** [comment]
Testing now prob something I broke :P

**Comment by Madpeterz** [comment]
can you tell me what grid you test on as I would like to replicate fully.

**Comment by RussoTheDev** [comment]
Latest version of opensim (0.9.1.1) launched in standalone mode without any customization

**Comment by Madpeterz** [comment]
its still broken 
but this makes it less broken https://github.com/cinderblocks/libremetaverse/pull/46

**Comment by RussoTheDev** [comment]
Great, it solved the problem with white textures but now I have another one...
This is how avatar looks when I am connecting using lib:
![image](https://user-images.githubusercontent.com/81874952/113491875-5dfdb480-94ed-11eb-9c8d-9f98b3ceafa1.png)
This is how it looks when connecting via firestorm:
![image](https://user-images.githubusercontent.com/81874952/113491892-7f5ea080-94ed-11eb-9a7c-81fd89a69a7d.png)

I am using a little bit customized version of metaverse lib (was forced to remove some stuff to make it run inside unity). Do you think the problem inside lib or maybe somewhere else? Looks like texture alpha was baked as black color

**Comment by Madpeterz** [comment]
... stuggling to get firestorm to connect to localhost
libmeta via my bot was easy :/

**Comment by RussoTheDev** [comment]
Here is my OpenSim binaries. it configured to 127.0.0.1:9000 https://drive.google.com/file/d/1_v_Om0xD3GUEHVxgvKma8o9tdoyfV4on/view?usp=sharing
Just start opensim.exe and add 127.0.0.1:9000 grid in fs to get it work
![image](https://user-images.githubusercontent.com/81874952/113492585-de261900-94f1-11eb-875d-032be222cc57.png)

**Comment by Madpeterz** [comment]
the issue is not just you
![image](https://user-images.githubusercontent.com/57852827/113492781-01d96700-94d2-11eb-8502-9241616f3300.png)

working on it now ^+^

**Comment by Madpeterz** [comment]
also I found my issue when firestorm tried to load the region it changed the port to 8002

**Comment by Madpeterz** [comment]
giving up for tonight if you find it let me know :P 
will try again in the morning

from what I can tell the head tat texture is being set to NULL_KEY and never being set,

**Comment by RussoTheDev** [comment]
Alright, may I ask you to give me possible direction of investigation? Where to dig?

**Comment by Madpeterz** [comment]
turns out this issue was because of me stopping a crash when alpha was out of bounds
![image](https://user-images.githubusercontent.com/57852827/113503660-3c232280-952b-11eb-8ec9-1142c3c0f932.png)

pull/46 should now correct to match the image
bake and appearance do need some more love thou

**Comment by RussoTheDev** [comment]
Great job, thank you

**Comment by cinderblocks** [comment]
PR accepted in 1.6.2
