### ISSUE TITLE
Nuget certificate signing for package is failing (Windows)

### ISSUE THREAD

**Issue by Madpeterz** [cinderblocks/libremetaverse#51]
see: https://ci.appveyor.com/project/cinderblocks57647/libremetaverse-ksbcr/builds/41497303

**Comment by cinderblocks** [comment]
The certificate has expired, and unfortunately, I do not have $399 USD right now to renew it.

**Comment by cinderblocks** [comment]
Pending CA verification...

**Comment by cinderblocks** [comment]
New certificate deployed.
