### ISSUE TITLE
client.Inventory.RemoveFolder fails

### ISSUE THREAD

**Issue by Jercieblue** [cinderblocks/libremetaverse#63]
Dear Sirs and friends,
I am trying to delete a folder from the root directory and seems that the folders still remains while the CreateFolder works perfect

Dim test_folder As String = "RoboBuddy Received Items"
Dim items As New List(Of KeyValuePair(Of UUID, InventoryNode))
For Each item In client.Inventory.Store.Items
    If item.Value.ToString() = test_folder Then
        items.Add(item)
    End If
Next

For Each item In items
    client.Inventory.RemoveFolder(item.Key)
Next

in the above code what i am doing is i passing each pair into a new list and then removing each uuid from the store to avoid list collection modification change.

Do i need to do anything additional?

Best regards

**Comment by cinderblocks** [comment]
I'm not sure why you are trying to do it this way. If you are trying to remove a Node why not simply use `Inventory.RemoveNodeFor(InventoryBase)` or `Inventory.RemoveDescendants(UUID)` or `Remove(List<UUID> items, List<UUID> folders)`? You can't use a folder removal function to remove inventory items.

**Comment by Jercieblue** [comment]
i want to remove the folder itself, is empty, also i am doing this way only not modify the underlaying list. it still fails even if i try to remove a single empty directory. It does remove it from the store list, but seems there is a problem updating the server so when you relog, the folder is still there

**Comment by cinderblocks** [comment]
Viewers don't typically remove folders from the inventory service like that. They move them to Trash.

**Comment by Jercieblue** [comment]
https://prnt.sc/26i6k8d

Not in trash either, they are there.

**Comment by cinderblocks** [comment]
RemoveFolder() doesn't move nodes to Trash. It appears Remove() and RemoveFolder() were never updated for AIS so this is a bug.

**Comment by cinderblocks** [comment]
Fixed in 1.9.19
