### ISSUE TITLE
_packetInbox unexpectedly null under certain sequence of events

### ISSUE THREAD

**Issue by aiwaiwa** [cinderblocks/libremetaverse#80]
This is observed after a (vaguely observed) failed teleport event and an attempt to log out when the network seems to already log out the avatar. The evidence of this is a log message `Ignoring RequestLogout(), client is already logged out` that precedes the outcome below in the NetworkManager `public void Shutdown(DisconnectType type, string message)`.

![image](https://user-images.githubusercontent.com/102391810/212556471-886540dc-2deb-4eef-a166-55aa141c63db.png)

Knowing how flimsy the logging out and teleporting is, I wonder if this can be somehow addressed internally in the library, or rather it would be advisable to intercept the error on a higher level?

The stack seems to begin with the Logout():
```
 	LibreMetaverse.dll!OpenMetaverse.NetworkManager.Shutdown(OpenMetaverse.NetworkManager.DisconnectType type, string message) Line 856	C#
>	LibreMetaverse.dll!OpenMetaverse.NetworkManager.Logout() Line 729	C#
```

**Comment by cinderblocks** [comment]
Just going to ignore the exception. If the packetInbox is already destroyed and we're shutting down, it's a non-issue, teardown fragility aside.
