### ISSUE TITLE
A syntax error creeped in during the #17f5c18d cleanup

### ISSUE THREAD

**Issue by aiwaiwa** [cinderblocks/libremetaverse#81]
There's a missing parenthesis now in this expression:
[
LibreMetaverse/AvatarManager.cs](https://github.com/cinderblocks/libremetaverse/commit/17f5c18d1986f1c43a6caa45a99e225fa3e49de1#diff-2a9c04e752845364ddcbb57e753236c82d24a8a143a01fd700561b190e975c7c)

` return (Client.Network.CurrentSim?.Caps?.CapabilityURI("GetDisplayNames") != null;`

**Comment by cinderblocks** [comment]
This is not an error.

**Comment by cinderblocks** [comment]
You are right. Thanks.
