### ISSUE TITLE
Missing Registration for ObjectAnimationEvent

### ISSUE THREAD

**Issue by alex8430** [cinderblocks/libremetaverse#91]
I have encountered an issue with the Librametaverse library where the ObjectAnimationEvent is not registered, I attempted to extend the existing ObjectManager class to support this event, following a pattern similar to AvatarAnimationEvent in the AvatarManager class, but I encountered difficulties and was unable to succeed.

Questions:

1. Is there a specific reason why ObjectAnimationEvent was not included in the library or registered with the ObjectManager class?
2. Could someone please provide guidance or suggestions on the correct approach to extend the ObjectManager class to support ObjectAnimationEvent?

**Comment by Madpeterz** [comment]
texture animations for objects are under the ObjectUpdate event is there some other event your looking for?

Events of note for objects:
TerseObjectUpdate
ObjectUpdate

**Comment by alex8430** [comment]
> texture animations for objects are under the ObjectUpdate event is there some other event your looking for?
> 
> Events of note for objects: TerseObjectUpdate ObjectUpdate

**Comment by cinderblocks** [comment]
"Is there a specific reason why ObjectAnimationEvent was not included in the library or registered with the ObjectManager class?"
Because this library is 18 years old and no one has contributed support for ObjectAnimation to it.

**Comment by alex8430** [comment]
@Madpeterz 
Thanks for your response. However, I'm not looking for texture animation. I'm specifically interested in non-avatar meshes like animals found in Second Life's Centauria land. These animals are skinned-mesh objects with animations applied to them. I'd like to understand the events responsible for animating these objects.
