### ISSUE TITLE
Hello from the SL Mobile Team (and how would you like us to give you our patches?)

### ISSUE THREAD

**Issue by AdamFrisby** [cinderblocks/libremetaverse#94]
Hi Cinder (and/or any other maintainers).

I just wanted to reach out from the SL Mobile Team, which I am working with; we've been using LibreMetaverse extensively for the SL Mobile project, and we'd like to give back the fixes and improvements we've cooked up over the past year and a bit.

We've got [a branch](https://github.com/secondlife/libremetaverse/commits/secondlife-mobile-patches-august2024/) that we'd like to open a PR on; but there's a _lot_ of fixes, and it might benefit from a short discussion first on how you'd like us to contribute these back, versus us surprising you with a monolithic PR.

We're not sure what's the best email address or method of contact is - but if possible, could you drop me a short email at adam@sinewavecompany.com, or let me know what your preferred contact method is?

Thankyou for your hard work maintaining the library!

**Comment by AdamFrisby** [comment]
Haha, we're not that bad .... _yet_. I'll shoot an email over in a moment.

**Comment by toxalph** [comment]
Hi @AdamFrisby and cinderblocks - sorry for thread hijacking, but I'm trying to integrate a libremetaverse client with webrtc and wondering if you can put me to any code or docs that will help? The SL wiki page was useful but lacking in details. I got as far as hitting the ProvisionVoiceAccountRequest caps but for some reason it gives me the response for vivox still.

Thanks for your help.

**Comment by AdamFrisby** [comment]
Give it a try in a webrtc enabled simulator -- there's a few WebRTC ones you can try; if that doesn't help, I'm semi familiar with that functionality and may be able to help if you can give me some specific questions.

(I'll also need to check it's okay, but I don't think that'll be an issue)

**Comment by toxalph** [comment]
Thanks a lot @AdamFrisby 

I went to the sim "WebRTC Voice 1" on agni with same results:

Seed caps url: `https://simhost-01d3500f306966b31.agni.secondlife.io:12043/cap/redacted guid`
Payload: 
```
<llsd>
	<array>
		<string>ProvisionVoiceAccountRequest</string>
		<string>VoiceSignalingRequest</string>
	</array>
</llsd>
```
Response: 
```
<llsd>
	<map>
		<key>Metadata</key>
		<map>
			<key>GetMesh</key>
			<map>
				<key>throttle</key>
				<integer>100</integer>
				<key>use-ssl</key>
				<boolean>0</boolean>
			</map>
			<key>GetMesh2</key>
			<map>
				<key>throttle</key>
				<integer>100</integer>
				<key>use-ssl</key>
				<boolean>0</boolean>
			</map>
			<key>GetTexture</key>
			<map>
				<key>throttle</key>
				<integer>100</integer>
				<key>use-ssl</key>
				<boolean>0</boolean>
			</map>
			<key>InventoryAPIv3</key>
			<map>
				<key>extended-methods</key>
				<boolean>1</boolean>
			</map>
			<key>InventoryThumbnailUpload</key>
			<map>
				<key>extended-methods</key>
				<boolean>1</boolean>
			</map>
			<key>LibraryAPIv3</key>
			<map>
				<key>extended-methods</key>
				<boolean>1</boolean>
			</map>
			<key>ViewerAsset</key>
			<map>
				<key>throttle</key>
				<integer>100</integer>
				<key>use-ssl</key>
				<boolean>0</boolean>
			</map>
			<key>viewer_uses_benefits</key>
			<boolean>0</boolean>
		</map>
		<key>ProvisionVoiceAccountRequest</key>
		<string>https://simhost-01d3500f306966b31.agni.secondlife.io:12043/cap/redacted guid</string>
		<key>VoiceSignalingRequest</key>
		<string>https://simhost-01d3500f306966b31.agni.secondlife.io:12043/cap/redacted guid</string>
	</map>
</llsd>
```

ProvisionVoiceAccountRequest url (as per above): `https://simhost-01d3500f306966b31.agni.secondlife.io:12043/cap/redacted guid`
Payload (as per https://webrtc-public-voice-beta.s3.us-west-2.amazonaws.com/WebRTC+on+Second+Life%2C+a+Developer's+View.pdf): 
```
<llsd>
	<map>
		<key>jsep</key>
		<map>
			<key>type</key>
			<string>offer
			</key>
			<key>sdp</key>
			<string>a=fmtp:minptime=10;useinbandfec=1;stereo=1;sprop-stereo=1;maxplaybackrate=48000</string>
		</map>
		<key>channel_type</key>
		<string>local</string>
		<key>voice_server_type</key>
		<string>webrtc</string>
	<map>
</llsd>
```
Response: 
```
<llsd>
	<map>
		<key>password</key>
		<string>redacted password</string>
		<key>username</key>
		<string>redacted username</string>
		<key>voice_account_server_name</key>
		<string>https://www.bhr.vivox.com/api2/</string>
		<key>voice_sip_uri_hostname</key>
		<string>bhr.vivox.com</string>
	</map>
</llsd>
```

Any idea why I get vivox response from ProvisionVoiceAccountRequest?

**Comment by cinderblocks** [comment]
I would suggest reaching out to Signal Linden who worked on the protocol and backend. Any further discussion on this should be moved to https://github.com/cinderblocks/libremetaverse/discussions

I am working on a voice module as well but I am juggling several big projects at once in LMV.
