### ISSUE TITLE
AgentManager.cs Chat function does not allow zero-length messages to be sent

### ISSUE THREAD

**Issue by stonejohnson** [cinderblocks/libremetaverse#99]
AgentManager.cs Chat function does not allow zero-length messages to be sent, which breaks some RLV functionality in Radegast.   It would be great to be able to send zero-length messages.

On line 1603 of AgentManager.cs there is the line

            else if ((message.Length > 0) && (message.Length < 1000))

which kills zero-byte-length messages.  Maybe this is necessary for other stuff to work, but it kills these RLV functions when you get to the bottom of the folder tree - it's important to return a null message (and not a blank which is interpreted as a filename).  Changing the line to 

            else if ((message.Length >= 0) && (message.Length < 1000))

will fix the problem.  Alternately there could be an alternate call that would allow the zero-length message, e.g.,

ChatZ(string message, int channel, ChatType type, bool split, bool hidechunk)     same functionality but allows the zero-length message.

Note that this aspect of RLV used to work in Radegast (5 years ago?) so it was permitted to send the zero-length message.

**Comment by cinderblocks** [comment]
Fixed in commit 79936981. Will be available in 2.1.5
